"""Definicje palet kolorów aplikacji.

Przełączanie w UI: potrójne kliknięcie logo (default → midnight → rose).
Programowo: app.theme.apply_palette('midnight')
"""

PALETTE_DEFAULT = {
    'UiColors': {
        'MAIN_BG_COLOR': '#2c2c2e',
        'SECONDARY_BG_COLOR': '#0b3d91',
        'TOP_BAR_BG_COLOR': '#f8f9fa',
        'TOP_BAR_TEXT_COLOR': '#1565c0',
        'NAV_BAR_BG_COLOR': '#0b3d91',
        'LOGO_SOURCE': 'Images/logo_bez_tla1.png',
        'SCREEN_MAIN_TEXT_COLOR': '#ffffff',
        'SCREEN_SECONDARY_TEXT_COLOR': '#ffffff',
    },
    'ButtonColors': {
        'TOP_BAR_BG_COLOR': '#9ea6b3',
        'TOP_BAR_TEXT_COLOR': '#000000',
        'NAV_BUTTON_BG_COLOR': '#2e588c',
        'NAV_BUTTON_TEXT_COLOR': '#ffffff',
        'NAV_BUTTON_PRESSED_BG_COLOR': '#f8f9fa',
        'NAV_BUTTON_PRESSED_TEXT_COLOR': '#000000',
        'SUBJECT_PLUS_BG_COLOR': '#c0392b',
        'SUBJECT_MINUS_BG_COLOR': '#2980b9',
        'SUBJECT_PLUS_TEXT_COLOR': '#ffffff',
        'SUBJECT_MINUS_TEXT_COLOR': '#ffffff',
        'TRACKER_PLUS_BG_COLOR': '#5cb85c',
        'TRACKER_PLUS_TEXT_COLOR': '#ffffff',
        'TRACKER_MINUS_BG_COLOR': '#c94c4c',
        'TRACKER_MINUS_TEXT_COLOR': '#ffffff',
        'REMOVE_BG_COLOR': '#c0392b',
        'REMOVE_TEXT_COLOR': '#ffffff',
        'STANDARD_UI_BUTTON_BG_COLOR': '#2e588c',
        'STANDARD_UI_BUTTON_TEXT_COLOR': '#ffffff',
        'STANDARD_UI_BUTTON_HOVER_BG_COLOR': '#245073',
        'STANDARD_UI_BUTTON_PRESSED_BG_COLOR': '#1a3d5c',
        'STANDARD_UI_BUTTON_PRESSED_TEXT_COLOR': '#ffffff',
    },
    'SubjectColors': {
        'SUBJECT_BG_COLOR_COMPLETED': '#62c57b',
        'SUBJECT_BG_COLOR_ATRISK': '#f28b82',
        'SUBJECT_BG_COLOR_INPROGRESS': '#d9d9d7',
        'SUBJECT_BG_COLOR_FAILED': '#272724',
        'SUBJECT_TEXT_COLOR_BRIGHT': '#ffffff',
        'SUBJECT_TEXT_COLOR_DARK': '#000000',
    },
    'WidgetColors': {
        'FORM_TEXTINPUT_BG_COLOR': '#322d2d',
        'FORM_TEXTINPUT_TEXT_COLOR': '#ffffff',
        'FORM_TEXTINPUT_FOCUS_BORDER': '#ffffff',
        'SCROLLBAR_COLOR_ACTIVE': '#888888',
        'SCROLLBAR_COLOR_INACTIVE': '#666666',
        'PROGRESSBAR_LOW': '#62c57b',
        'PROGRESSBAR_MID': '#f1c40f',
        'PROGRESSBAR_HIGH': '#e74c3c',
        'PROGRESSCARD_BG_COLOR': '#e0e0e0',
        'PROGRESSCARD_TEXT_COLOR': '#000000',
        'PROGRESSCARD_SECONDARY_TEXT_COLOR': '#333333',
    },
    'CalendarColors': {
        'LESSON_BG_COLOR': '#86a6c1',
        'LESSON_HOVER_BG_COLOR': '#7092ad',
        'EXAM_BG_COLOR': '#e57373',
        'EXAM_HOVER_BG_COLOR': '#ef5350',
        'COLOQUIUM_BG_COLOR': '#ffb74d',
        'COLOQUIUM_HOVER_BG_COLOR': '#ffa726',
    },
    'DefaultColors': {
        'DEFAULT_WHITE': '#ffffff',
        'DEFAULT_BLACK': '#000000',
    },
}

# Ciemny motyw „Midnight” — fioletowo-granatowe tło, miękkie akcenty Tokyo Night.
PALETTE_MIDNIGHT = {
    'UiColors': {
        'MAIN_BG_COLOR': '#1a1b26',
        'SECONDARY_BG_COLOR': '#24283b',
        'TOP_BAR_BG_COLOR': '#16161e',
        'TOP_BAR_TEXT_COLOR': '#7dcfff',
        'NAV_BAR_BG_COLOR': '#24283b',
        'LOGO_SOURCE': 'Images/logo_theme_midnight.png',
        'SCREEN_MAIN_TEXT_COLOR': '#c0caf5',
        'SCREEN_SECONDARY_TEXT_COLOR': '#a9b1d6',
    },
    'ButtonColors': {
        'TOP_BAR_BG_COLOR': '#414868',
        'TOP_BAR_TEXT_COLOR': '#c0caf5',
        'NAV_BUTTON_BG_COLOR': '#565f89',
        'NAV_BUTTON_TEXT_COLOR': '#c0caf5',
        'NAV_BUTTON_PRESSED_BG_COLOR': '#7aa2f7',
        'NAV_BUTTON_PRESSED_TEXT_COLOR': '#1a1b26',
        'SUBJECT_PLUS_BG_COLOR': '#f7768e',
        'SUBJECT_MINUS_BG_COLOR': '#7aa2f7',
        'SUBJECT_PLUS_TEXT_COLOR': '#1a1b26',
        'SUBJECT_MINUS_TEXT_COLOR': '#1a1b26',
        'TRACKER_PLUS_BG_COLOR': '#9ece6a',
        'TRACKER_PLUS_TEXT_COLOR': '#1a1b26',
        'TRACKER_MINUS_BG_COLOR': '#ff7575',
        'TRACKER_MINUS_TEXT_COLOR': '#1a1b26',
        'REMOVE_BG_COLOR': '#db4b4b',
        'REMOVE_TEXT_COLOR': '#ffffff',
        'STANDARD_UI_BUTTON_BG_COLOR': '#7aa2f7',
        'STANDARD_UI_BUTTON_TEXT_COLOR': '#1a1b26',
        'STANDARD_UI_BUTTON_HOVER_BG_COLOR': '#89b4ff',
        'STANDARD_UI_BUTTON_PRESSED_BG_COLOR': '#565f89',
        'STANDARD_UI_BUTTON_PRESSED_TEXT_COLOR': '#c0caf5',
    },
    'SubjectColors': {
        'SUBJECT_BG_COLOR_COMPLETED': '#9ece6a',
        'SUBJECT_BG_COLOR_ATRISK': '#ff7575',
        'SUBJECT_BG_COLOR_INPROGRESS': '#565f89',
        'SUBJECT_BG_COLOR_FAILED': '#414868',
        'SUBJECT_TEXT_COLOR_BRIGHT': '#c0caf5',
        'SUBJECT_TEXT_COLOR_DARK': '#1a1b26',
    },
    'WidgetColors': {
        'FORM_TEXTINPUT_BG_COLOR': '#1f2335',
        'FORM_TEXTINPUT_TEXT_COLOR': '#c0caf5',
        'FORM_TEXTINPUT_FOCUS_BORDER': '#7dcfff',
        'SCROLLBAR_COLOR_ACTIVE': '#565f89',
        'SCROLLBAR_COLOR_INACTIVE': '#414868',
        'PROGRESSBAR_LOW': '#9ece6a',
        'PROGRESSBAR_MID': '#e0af68',
        'PROGRESSBAR_HIGH': '#f7768e',
        'PROGRESSCARD_BG_COLOR': '#24283b',
        'PROGRESSCARD_TEXT_COLOR': '#c0caf5',
        'PROGRESSCARD_SECONDARY_TEXT_COLOR': '#a9b1d6',
    },
    'CalendarColors': {
        'LESSON_BG_COLOR': '#3d59a1',
        'LESSON_HOVER_BG_COLOR': '#2f4778',
        'EXAM_BG_COLOR': '#f7768e',
        'EXAM_HOVER_BG_COLOR': '#e06b85',
        'COLOQUIUM_BG_COLOR': '#e0af68',
        'COLOQUIUM_HOVER_BG_COLOR': '#c99552',
    },
    'DefaultColors': {
        'DEFAULT_WHITE': '#c0caf5',
        'DEFAULT_BLACK': '#1a1b26',
    },
}

# Motyw „Rose” — ciepłe tło, akcenty w odcieniach różu i fuchsia.
PALETTE_ROSE = {
    'UiColors': {
        'MAIN_BG_COLOR': '#1f1518',
        'SECONDARY_BG_COLOR': '#3d2433',
        'TOP_BAR_BG_COLOR': '#2a1a22',
        'TOP_BAR_TEXT_COLOR': '#f4a6c8',
        'NAV_BAR_BG_COLOR': '#3d2433',
        'LOGO_SOURCE': 'Images/logo_theme_rose.png',
        'SCREEN_MAIN_TEXT_COLOR': '#fde2f0',
        'SCREEN_SECONDARY_TEXT_COLOR': '#f4c2d7',
    },
    'ButtonColors': {
        'TOP_BAR_BG_COLOR': '#5c3a4a',
        'TOP_BAR_TEXT_COLOR': '#fde2f0',
        'NAV_BUTTON_BG_COLOR': '#8e4a6b',
        'NAV_BUTTON_TEXT_COLOR': '#ffffff',
        'NAV_BUTTON_PRESSED_BG_COLOR': '#f4a6c8',
        'NAV_BUTTON_PRESSED_TEXT_COLOR': '#1f1518',
        'SUBJECT_PLUS_BG_COLOR': '#e06c9f',
        'SUBJECT_MINUS_BG_COLOR': '#b565a7',
        'SUBJECT_PLUS_TEXT_COLOR': '#1f1518',
        'SUBJECT_MINUS_TEXT_COLOR': '#ffffff',
        'TRACKER_PLUS_BG_COLOR': '#d16ba5',
        'TRACKER_PLUS_TEXT_COLOR': '#1f1518',
        'TRACKER_MINUS_BG_COLOR': '#c94c7e',
        'TRACKER_MINUS_TEXT_COLOR': '#ffffff',
        'REMOVE_BG_COLOR': '#c94c7e',
        'REMOVE_TEXT_COLOR': '#ffffff',
        'STANDARD_UI_BUTTON_BG_COLOR': '#d16ba5',
        'STANDARD_UI_BUTTON_TEXT_COLOR': '#1f1518',
        'STANDARD_UI_BUTTON_HOVER_BG_COLOR': '#e88fbc',
        'STANDARD_UI_BUTTON_PRESSED_BG_COLOR': '#f4a6c8',
        'STANDARD_UI_BUTTON_PRESSED_TEXT_COLOR': '#1f1518',
    },
    'SubjectColors': {
        'SUBJECT_BG_COLOR_COMPLETED': '#e88fbc',
        'SUBJECT_BG_COLOR_ATRISK': '#ff8fab',
        'SUBJECT_BG_COLOR_INPROGRESS': '#5c3a4a',
        'SUBJECT_BG_COLOR_FAILED': '#3d2433',
        'SUBJECT_TEXT_COLOR_BRIGHT': '#fde2f0',
        'SUBJECT_TEXT_COLOR_DARK': '#1f1518',
    },
    'WidgetColors': {
        'FORM_TEXTINPUT_BG_COLOR': '#2a1a22',
        'FORM_TEXTINPUT_TEXT_COLOR': '#fde2f0',
        'FORM_TEXTINPUT_FOCUS_BORDER': '#f4a6c8',
        'SCROLLBAR_COLOR_ACTIVE': '#8e4a6b',
        'SCROLLBAR_COLOR_INACTIVE': '#5c3a4a',
        'PROGRESSBAR_LOW': '#e88fbc',
        'PROGRESSBAR_MID': '#f4a6c8',
        'PROGRESSBAR_HIGH': '#ff8fab',
        'PROGRESSCARD_BG_COLOR': '#3d2433',
        'PROGRESSCARD_TEXT_COLOR': '#fde2f0',
        'PROGRESSCARD_SECONDARY_TEXT_COLOR': '#f4c2d7',
    },
    'CalendarColors': {
        'LESSON_BG_COLOR': '#b565a7',
        'LESSON_HOVER_BG_COLOR': '#9a558f',
        'EXAM_BG_COLOR': '#ff8fab',
        'EXAM_HOVER_BG_COLOR': '#e07a96',
        'COLOQUIUM_BG_COLOR': '#f4a6c8',
        'COLOQUIUM_HOVER_BG_COLOR': '#d889ad',
    },
    'DefaultColors': {
        'DEFAULT_WHITE': '#fde2f0',
        'DEFAULT_BLACK': '#1f1518',
    },
}

PALETTES = {
    'default': PALETTE_DEFAULT,
    'midnight': PALETTE_MIDNIGHT,
    'rose': PALETTE_ROSE,
}

DEFAULT_PALETTE_NAME = 'default'
