#:import ButtonStyle Widgets.Button.ButtonStyle
#:import Shapes Widgets.Button.Shapes

BoxLayout
    orientation: 'vertical'
    padding: 20
    spacing: 50
    StandardUiButton:
        text: "Start / Kalendarz"

    BoxLayout:
        orientation: 'horizontal'  # Kafelki obok siebie
        spacing: 10
        padding: 20
        
            
        # Kafelek nr 1
        BlueBrick:
            title_text: "SK"
            info_text: "10:30 | 1.5h"
            has_note: True


        # Kafelek nr 2
        BlueBrick:
            title_text: "WF"
            info_text: "12:00 | 1.0h"
            has_note: False
        

        # Kafelek nr 3
        BlueBrick:
            title_text: "MAT"
            info_text: "13:30 | 2.0h"